sonar.projectKey=house-price-prediction-using-flask
sonar.organization=maheshpasapala

sonar.sources=app.py,house.py
sonar.tests=tests

sonar.exclusions=**/*.csv,**/*.pkl,**/static/images/**,**/__pycache__/**,**/.pytest_cache/**,**/build-wrapper-dump.json,**/tests/**

sonar.test.inclusions=**/tests/**/*.py