sonar.projectKey=house-price-prediction-using-flask
sonar.projectName=House Price Prediction Using Flask
sonar.organization=maheshpasapala
sonar.sources=.
sonar.tests=tests
sonar.python.version=3.9
sonar.qualitygate.wait=true
sonar.exclusions=**/*.csv,**/*.pkl,**/static/images/**,**/__pycache__/**,**/.pytest_cache/**